### PR TITLE
add dependencies for notebooks

### PR DESCRIPTION
**Pull request by alexferrante**
Added dependencies needed for running notebooks

### CODE REVIEW

**Review by vianamp — COMMENTED** [review]
Do you know what these packages are used for? I don't recall using anything like this..

**Comment by alexferrante** [comment]
I got the indication that I needed`ipywidgets` was needed because of `tqdm`; I wasn't able to run the notebooks involving progress bars

I needed `jupyterlab` to be able to start a Jupyter notebook instance via slurm

it's possible that these dependencies are specific to our environment. does everything work for you without these packages?

**Comment by vianamp** [comment]
Yeah, it does work. They are heavy package dependencies, but I think it is fine to keep it in. Most of people at the institute will be running the repo from Slurm anyways. Do you agree?

**Comment by alexferrante** [comment]
sounds good to me. maybe we can revisit if more people adopt Gui's jupyter hub, which presumable takes care of these dependencies.

**Pull request merged**
